#!/bin/bash
gcc -c $CFILE
[A[C[C
[D[D[B[A[A[[A[C[C[C[C[C[C[C[C[C[C[C[C[C


[A[A[A[C[C[C[C[C[C[C[C[C[C[C[C[C:
[A[C[C[C[C[C[C[C[C[C[C[C[C[C
[A[Bhp@Grace MINGW64 ~/alx-low_level_programming/0x00-hello_world (main)
[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Ccd -
[A[A[B[C[C
[A
[A[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Dd
[A[C[C[C[C[C[C[C[C[C[C[C[C[C[F[B[C[C[C[C[C[C[C[C[C[C[C[C[C
